package org.cms.persistence.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.cms.persistence.model.UcBlog;
import org.cms.persistence.model.UcBlogExample;

public interface UcBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    int countByExample(UcBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    int deleteByExample(UcBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    @Delete({
        "delete from uc_blog",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    @Insert({
        "insert into uc_blog (id, created_at, ",
        "creator, modifier, ",
        "updated_at, member_id, ",
        "category_id, interest_id, ",
        "content_id, title, ",
        "tags, short_image, ",
        "description, audit_status, ",
        "delete_flag, posted_flag, ",
        "draft_flag, recommend_flag, ",
        "comment_count, visit_count, ",
        "refuse_cause, refuse_count, ",
        "member_type, vip_flag)",
        "values (#{id,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=VARCHAR}, #{modifier,jdbcType=VARCHAR}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{memberId,jdbcType=INTEGER}, ",
        "#{categoryId,jdbcType=INTEGER}, #{interestId,jdbcType=INTEGER}, ",
        "#{contentId,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{tags,jdbcType=VARCHAR}, #{shortImage,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{auditStatus,jdbcType=TINYINT}, ",
        "#{deleteFlag,jdbcType=TINYINT}, #{postedFlag,jdbcType=TINYINT}, ",
        "#{draftFlag,jdbcType=TINYINT}, #{recommendFlag,jdbcType=TINYINT}, ",
        "#{commentCount,jdbcType=INTEGER}, #{visitCount,jdbcType=INTEGER}, ",
        "#{refuseCause,jdbcType=VARCHAR}, #{refuseCount,jdbcType=SMALLINT}, ",
        "#{memberType,jdbcType=TINYINT}, #{vipFlag,jdbcType=TINYINT})"
    })
    int insert(UcBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    int insertSelective(UcBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    List<UcBlog> selectByExample(UcBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, created_at, creator, modifier, updated_at, member_id, category_id, interest_id, ",
        "content_id, title, tags, short_image, description, audit_status, delete_flag, ",
        "posted_flag, draft_flag, recommend_flag, comment_count, visit_count, refuse_cause, ",
        "refuse_count, member_type, vip_flag",
        "from uc_blog",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UcBlog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UcBlog record, @Param("example") UcBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UcBlog record, @Param("example") UcBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UcBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    @Update({
        "update uc_blog",
        "set created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "modifier = #{modifier,jdbcType=VARCHAR},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "member_id = #{memberId,jdbcType=INTEGER},",
          "category_id = #{categoryId,jdbcType=INTEGER},",
          "interest_id = #{interestId,jdbcType=INTEGER},",
          "content_id = #{contentId,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "tags = #{tags,jdbcType=VARCHAR},",
          "short_image = #{shortImage,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "audit_status = #{auditStatus,jdbcType=TINYINT},",
          "delete_flag = #{deleteFlag,jdbcType=TINYINT},",
          "posted_flag = #{postedFlag,jdbcType=TINYINT},",
          "draft_flag = #{draftFlag,jdbcType=TINYINT},",
          "recommend_flag = #{recommendFlag,jdbcType=TINYINT},",
          "comment_count = #{commentCount,jdbcType=INTEGER},",
          "visit_count = #{visitCount,jdbcType=INTEGER},",
          "refuse_cause = #{refuseCause,jdbcType=VARCHAR},",
          "refuse_count = #{refuseCount,jdbcType=SMALLINT},",
          "member_type = #{memberType,jdbcType=TINYINT},",
          "vip_flag = #{vipFlag,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UcBlog record);
}