package org.cms.persistence.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.cms.persistence.model.UcMember;
import org.cms.persistence.model.UcMemberExample;

public interface UcMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    int countByExample(UcMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    int deleteByExample(UcMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    @Delete({
        "delete from uc_member",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    @Insert({
        "insert into uc_member (id, created_at, ",
        "creator, modifier, ",
        "updated_at, member_info_id, ",
        "expert_id, enterprise_id, ",
        "nickname, title, ",
        "sex, age, birthday, ",
        "mobile, email, qq, ",
        "photo, province_id, ",
        "city_id, country_id, ",
        "introduce, remark, ",
        "visit_count, day_visit_count, ",
        "day_visit_time, delete_flag, ",
        "disable_flag, mobile_verify_flag, ",
        "email_verify_flag, audit_flag, ",
        "open_concat_flag, show_flag, ",
        "email_remind_flag, blog_flag, ",
        "realname_audit_status, audit_reason, ",
        "expert_audit_status, expert_info_audit_status, ",
        "enterprise_audit_status, enterprise_info_audit_status, ",
        "mod_flag, res_mod_update, ",
        "safe_score, safe_next_id, ",
        "vip_level, vip_startdate, ",
        "vip_enddate)",
        "values (#{id,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{creator,jdbcType=VARCHAR}, #{modifier,jdbcType=VARCHAR}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{memberInfoId,jdbcType=INTEGER}, ",
        "#{expertId,jdbcType=INTEGER}, #{enterpriseId,jdbcType=INTEGER}, ",
        "#{nickname,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=TINYINT}, #{age,jdbcType=INTEGER}, #{birthday,jdbcType=TIMESTAMP}, ",
        "#{mobile,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, #{qq,jdbcType=VARCHAR}, ",
        "#{photo,jdbcType=VARCHAR}, #{provinceId,jdbcType=INTEGER}, ",
        "#{cityId,jdbcType=INTEGER}, #{countryId,jdbcType=INTEGER}, ",
        "#{introduce,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{visitCount,jdbcType=INTEGER}, #{dayVisitCount,jdbcType=INTEGER}, ",
        "#{dayVisitTime,jdbcType=TIMESTAMP}, #{deleteFlag,jdbcType=TINYINT}, ",
        "#{disableFlag,jdbcType=TINYINT}, #{mobileVerifyFlag,jdbcType=TINYINT}, ",
        "#{emailVerifyFlag,jdbcType=TINYINT}, #{auditFlag,jdbcType=TINYINT}, ",
        "#{openConcatFlag,jdbcType=TINYINT}, #{showFlag,jdbcType=TINYINT}, ",
        "#{emailRemindFlag,jdbcType=TINYINT}, #{blogFlag,jdbcType=TINYINT}, ",
        "#{realnameAuditStatus,jdbcType=TINYINT}, #{auditReason,jdbcType=VARCHAR}, ",
        "#{expertAuditStatus,jdbcType=TINYINT}, #{expertInfoAuditStatus,jdbcType=TINYINT}, ",
        "#{enterpriseAuditStatus,jdbcType=TINYINT}, #{enterpriseInfoAuditStatus,jdbcType=TINYINT}, ",
        "#{modFlag,jdbcType=TINYINT}, #{resModUpdate,jdbcType=TIMESTAMP}, ",
        "#{safeScore,jdbcType=INTEGER}, #{safeNextId,jdbcType=INTEGER}, ",
        "#{vipLevel,jdbcType=TINYINT}, #{vipStartdate,jdbcType=DATE}, ",
        "#{vipEnddate,jdbcType=DATE})"
    })
    int insert(UcMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    int insertSelective(UcMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    List<UcMember> selectByExample(UcMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, created_at, creator, modifier, updated_at, member_info_id, expert_id, enterprise_id, ",
        "nickname, title, sex, age, birthday, mobile, email, qq, photo, province_id, ",
        "city_id, country_id, introduce, remark, visit_count, day_visit_count, day_visit_time, ",
        "delete_flag, disable_flag, mobile_verify_flag, email_verify_flag, audit_flag, ",
        "open_concat_flag, show_flag, email_remind_flag, blog_flag, realname_audit_status, ",
        "audit_reason, expert_audit_status, expert_info_audit_status, enterprise_audit_status, ",
        "enterprise_info_audit_status, mod_flag, res_mod_update, safe_score, safe_next_id, ",
        "vip_level, vip_startdate, vip_enddate",
        "from uc_member",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    UcMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UcMember record, @Param("example") UcMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UcMember record, @Param("example") UcMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UcMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    @Update({
        "update uc_member",
        "set created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "creator = #{creator,jdbcType=VARCHAR},",
          "modifier = #{modifier,jdbcType=VARCHAR},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "member_info_id = #{memberInfoId,jdbcType=INTEGER},",
          "expert_id = #{expertId,jdbcType=INTEGER},",
          "enterprise_id = #{enterpriseId,jdbcType=INTEGER},",
          "nickname = #{nickname,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=TINYINT},",
          "age = #{age,jdbcType=INTEGER},",
          "birthday = #{birthday,jdbcType=TIMESTAMP},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "qq = #{qq,jdbcType=VARCHAR},",
          "photo = #{photo,jdbcType=VARCHAR},",
          "province_id = #{provinceId,jdbcType=INTEGER},",
          "city_id = #{cityId,jdbcType=INTEGER},",
          "country_id = #{countryId,jdbcType=INTEGER},",
          "introduce = #{introduce,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "visit_count = #{visitCount,jdbcType=INTEGER},",
          "day_visit_count = #{dayVisitCount,jdbcType=INTEGER},",
          "day_visit_time = #{dayVisitTime,jdbcType=TIMESTAMP},",
          "delete_flag = #{deleteFlag,jdbcType=TINYINT},",
          "disable_flag = #{disableFlag,jdbcType=TINYINT},",
          "mobile_verify_flag = #{mobileVerifyFlag,jdbcType=TINYINT},",
          "email_verify_flag = #{emailVerifyFlag,jdbcType=TINYINT},",
          "audit_flag = #{auditFlag,jdbcType=TINYINT},",
          "open_concat_flag = #{openConcatFlag,jdbcType=TINYINT},",
          "show_flag = #{showFlag,jdbcType=TINYINT},",
          "email_remind_flag = #{emailRemindFlag,jdbcType=TINYINT},",
          "blog_flag = #{blogFlag,jdbcType=TINYINT},",
          "realname_audit_status = #{realnameAuditStatus,jdbcType=TINYINT},",
          "audit_reason = #{auditReason,jdbcType=VARCHAR},",
          "expert_audit_status = #{expertAuditStatus,jdbcType=TINYINT},",
          "expert_info_audit_status = #{expertInfoAuditStatus,jdbcType=TINYINT},",
          "enterprise_audit_status = #{enterpriseAuditStatus,jdbcType=TINYINT},",
          "enterprise_info_audit_status = #{enterpriseInfoAuditStatus,jdbcType=TINYINT},",
          "mod_flag = #{modFlag,jdbcType=TINYINT},",
          "res_mod_update = #{resModUpdate,jdbcType=TIMESTAMP},",
          "safe_score = #{safeScore,jdbcType=INTEGER},",
          "safe_next_id = #{safeNextId,jdbcType=INTEGER},",
          "vip_level = #{vipLevel,jdbcType=TINYINT},",
          "vip_startdate = #{vipStartdate,jdbcType=DATE},",
          "vip_enddate = #{vipEnddate,jdbcType=DATE}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UcMember record);
}