package org.cms.persistence.model;

import java.util.Date;

public class UcBlog extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.interest_id
     *
     * @mbggenerated
     */
    private Integer interestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.content_id
     *
     * @mbggenerated
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.short_image
     *
     * @mbggenerated
     */
    private String shortImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.audit_status
     *
     * @mbggenerated
     */
    private Byte auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.delete_flag
     *
     * @mbggenerated
     */
    private Byte deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.posted_flag
     *
     * @mbggenerated
     */
    private Byte postedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.draft_flag
     *
     * @mbggenerated
     */
    private Byte draftFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.recommend_flag
     *
     * @mbggenerated
     */
    private Byte recommendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.comment_count
     *
     * @mbggenerated
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.visit_count
     *
     * @mbggenerated
     */
    private Integer visitCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.refuse_cause
     *
     * @mbggenerated
     */
    private String refuseCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.refuse_count
     *
     * @mbggenerated
     */
    private Short refuseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.member_type
     *
     * @mbggenerated
     */
    private Byte memberType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_blog.vip_flag
     *
     * @mbggenerated
     */
    private Byte vipFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_blog
     *
     * @mbggenerated
     */
    public UcBlog(Integer id, Date createdAt, String creator, String modifier, Date updatedAt, Integer memberId, Integer categoryId, Integer interestId, Integer contentId, String title, String tags, String shortImage, String description, Byte auditStatus, Byte deleteFlag, Byte postedFlag, Byte draftFlag, Byte recommendFlag, Integer commentCount, Integer visitCount, String refuseCause, Short refuseCount, Byte memberType, Byte vipFlag) {
        this.id = id;
        this.createdAt = createdAt;
        this.creator = creator;
        this.modifier = modifier;
        this.updatedAt = updatedAt;
        this.memberId = memberId;
        this.categoryId = categoryId;
        this.interestId = interestId;
        this.contentId = contentId;
        this.title = title;
        this.tags = tags;
        this.shortImage = shortImage;
        this.description = description;
        this.auditStatus = auditStatus;
        this.deleteFlag = deleteFlag;
        this.postedFlag = postedFlag;
        this.draftFlag = draftFlag;
        this.recommendFlag = recommendFlag;
        this.commentCount = commentCount;
        this.visitCount = visitCount;
        this.refuseCause = refuseCause;
        this.refuseCount = refuseCount;
        this.memberType = memberType;
        this.vipFlag = vipFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.id
     *
     * @return the value of uc_blog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.created_at
     *
     * @return the value of uc_blog.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.creator
     *
     * @return the value of uc_blog.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.modifier
     *
     * @return the value of uc_blog.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.updated_at
     *
     * @return the value of uc_blog.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.member_id
     *
     * @return the value of uc_blog.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.category_id
     *
     * @return the value of uc_blog.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.interest_id
     *
     * @return the value of uc_blog.interest_id
     *
     * @mbggenerated
     */
    public Integer getInterestId() {
        return interestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.content_id
     *
     * @return the value of uc_blog.content_id
     *
     * @mbggenerated
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.title
     *
     * @return the value of uc_blog.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.tags
     *
     * @return the value of uc_blog.tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.short_image
     *
     * @return the value of uc_blog.short_image
     *
     * @mbggenerated
     */
    public String getShortImage() {
        return shortImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.description
     *
     * @return the value of uc_blog.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.audit_status
     *
     * @return the value of uc_blog.audit_status
     *
     * @mbggenerated
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.delete_flag
     *
     * @return the value of uc_blog.delete_flag
     *
     * @mbggenerated
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.posted_flag
     *
     * @return the value of uc_blog.posted_flag
     *
     * @mbggenerated
     */
    public Byte getPostedFlag() {
        return postedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.draft_flag
     *
     * @return the value of uc_blog.draft_flag
     *
     * @mbggenerated
     */
    public Byte getDraftFlag() {
        return draftFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.recommend_flag
     *
     * @return the value of uc_blog.recommend_flag
     *
     * @mbggenerated
     */
    public Byte getRecommendFlag() {
        return recommendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.comment_count
     *
     * @return the value of uc_blog.comment_count
     *
     * @mbggenerated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.visit_count
     *
     * @return the value of uc_blog.visit_count
     *
     * @mbggenerated
     */
    public Integer getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.refuse_cause
     *
     * @return the value of uc_blog.refuse_cause
     *
     * @mbggenerated
     */
    public String getRefuseCause() {
        return refuseCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.refuse_count
     *
     * @return the value of uc_blog.refuse_count
     *
     * @mbggenerated
     */
    public Short getRefuseCount() {
        return refuseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.member_type
     *
     * @return the value of uc_blog.member_type
     *
     * @mbggenerated
     */
    public Byte getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_blog.vip_flag
     *
     * @return the value of uc_blog.vip_flag
     *
     * @mbggenerated
     */
    public Byte getVipFlag() {
        return vipFlag;
    }
}