package org.cms.persistence.model;

import java.util.Date;

public class UcMember extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.member_info_id
     *
     * @mbggenerated
     */
    private Integer memberInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.expert_id
     *
     * @mbggenerated
     */
    private Integer expertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.enterprise_id
     *
     * @mbggenerated
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.photo
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.province_id
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.city_id
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.country_id
     *
     * @mbggenerated
     */
    private Integer countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.visit_count
     *
     * @mbggenerated
     */
    private Integer visitCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.day_visit_count
     *
     * @mbggenerated
     */
    private Integer dayVisitCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.day_visit_time
     *
     * @mbggenerated
     */
    private Date dayVisitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.delete_flag
     *
     * @mbggenerated
     */
    private Byte deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.disable_flag
     *
     * @mbggenerated
     */
    private Byte disableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.mobile_verify_flag
     *
     * @mbggenerated
     */
    private Byte mobileVerifyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.email_verify_flag
     *
     * @mbggenerated
     */
    private Byte emailVerifyFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.audit_flag
     *
     * @mbggenerated
     */
    private Byte auditFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.open_concat_flag
     *
     * @mbggenerated
     */
    private Byte openConcatFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.show_flag
     *
     * @mbggenerated
     */
    private Byte showFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.email_remind_flag
     *
     * @mbggenerated
     */
    private Byte emailRemindFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.blog_flag
     *
     * @mbggenerated
     */
    private Byte blogFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.realname_audit_status
     *
     * @mbggenerated
     */
    private Byte realnameAuditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.audit_reason
     *
     * @mbggenerated
     */
    private String auditReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.expert_audit_status
     *
     * @mbggenerated
     */
    private Byte expertAuditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.expert_info_audit_status
     *
     * @mbggenerated
     */
    private Byte expertInfoAuditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.enterprise_audit_status
     *
     * @mbggenerated
     */
    private Byte enterpriseAuditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.enterprise_info_audit_status
     *
     * @mbggenerated
     */
    private Byte enterpriseInfoAuditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.mod_flag
     *
     * @mbggenerated
     */
    private Byte modFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.res_mod_update
     *
     * @mbggenerated
     */
    private Date resModUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.safe_score
     *
     * @mbggenerated
     */
    private Integer safeScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.safe_next_id
     *
     * @mbggenerated
     */
    private Integer safeNextId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.vip_level
     *
     * @mbggenerated
     */
    private Byte vipLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.vip_startdate
     *
     * @mbggenerated
     */
    private Date vipStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_member.vip_enddate
     *
     * @mbggenerated
     */
    private Date vipEnddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_member
     *
     * @mbggenerated
     */
    public UcMember(Integer id, Date createdAt, String creator, String modifier, Date updatedAt, Integer memberInfoId, Integer expertId, Integer enterpriseId, String nickname, String title, Byte sex, Integer age, Date birthday, String mobile, String email, String qq, String photo, Integer provinceId, Integer cityId, Integer countryId, String introduce, String remark, Integer visitCount, Integer dayVisitCount, Date dayVisitTime, Byte deleteFlag, Byte disableFlag, Byte mobileVerifyFlag, Byte emailVerifyFlag, Byte auditFlag, Byte openConcatFlag, Byte showFlag, Byte emailRemindFlag, Byte blogFlag, Byte realnameAuditStatus, String auditReason, Byte expertAuditStatus, Byte expertInfoAuditStatus, Byte enterpriseAuditStatus, Byte enterpriseInfoAuditStatus, Byte modFlag, Date resModUpdate, Integer safeScore, Integer safeNextId, Byte vipLevel, Date vipStartdate, Date vipEnddate) {
        this.id = id;
        this.createdAt = createdAt;
        this.creator = creator;
        this.modifier = modifier;
        this.updatedAt = updatedAt;
        this.memberInfoId = memberInfoId;
        this.expertId = expertId;
        this.enterpriseId = enterpriseId;
        this.nickname = nickname;
        this.title = title;
        this.sex = sex;
        this.age = age;
        this.birthday = birthday;
        this.mobile = mobile;
        this.email = email;
        this.qq = qq;
        this.photo = photo;
        this.provinceId = provinceId;
        this.cityId = cityId;
        this.countryId = countryId;
        this.introduce = introduce;
        this.remark = remark;
        this.visitCount = visitCount;
        this.dayVisitCount = dayVisitCount;
        this.dayVisitTime = dayVisitTime;
        this.deleteFlag = deleteFlag;
        this.disableFlag = disableFlag;
        this.mobileVerifyFlag = mobileVerifyFlag;
        this.emailVerifyFlag = emailVerifyFlag;
        this.auditFlag = auditFlag;
        this.openConcatFlag = openConcatFlag;
        this.showFlag = showFlag;
        this.emailRemindFlag = emailRemindFlag;
        this.blogFlag = blogFlag;
        this.realnameAuditStatus = realnameAuditStatus;
        this.auditReason = auditReason;
        this.expertAuditStatus = expertAuditStatus;
        this.expertInfoAuditStatus = expertInfoAuditStatus;
        this.enterpriseAuditStatus = enterpriseAuditStatus;
        this.enterpriseInfoAuditStatus = enterpriseInfoAuditStatus;
        this.modFlag = modFlag;
        this.resModUpdate = resModUpdate;
        this.safeScore = safeScore;
        this.safeNextId = safeNextId;
        this.vipLevel = vipLevel;
        this.vipStartdate = vipStartdate;
        this.vipEnddate = vipEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.id
     *
     * @return the value of uc_member.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.created_at
     *
     * @return the value of uc_member.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.creator
     *
     * @return the value of uc_member.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.modifier
     *
     * @return the value of uc_member.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.updated_at
     *
     * @return the value of uc_member.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.member_info_id
     *
     * @return the value of uc_member.member_info_id
     *
     * @mbggenerated
     */
    public Integer getMemberInfoId() {
        return memberInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.expert_id
     *
     * @return the value of uc_member.expert_id
     *
     * @mbggenerated
     */
    public Integer getExpertId() {
        return expertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.enterprise_id
     *
     * @return the value of uc_member.enterprise_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.nickname
     *
     * @return the value of uc_member.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.title
     *
     * @return the value of uc_member.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.sex
     *
     * @return the value of uc_member.sex
     *
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.age
     *
     * @return the value of uc_member.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.birthday
     *
     * @return the value of uc_member.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.mobile
     *
     * @return the value of uc_member.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.email
     *
     * @return the value of uc_member.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.qq
     *
     * @return the value of uc_member.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.photo
     *
     * @return the value of uc_member.photo
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.province_id
     *
     * @return the value of uc_member.province_id
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.city_id
     *
     * @return the value of uc_member.city_id
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.country_id
     *
     * @return the value of uc_member.country_id
     *
     * @mbggenerated
     */
    public Integer getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.introduce
     *
     * @return the value of uc_member.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.remark
     *
     * @return the value of uc_member.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.visit_count
     *
     * @return the value of uc_member.visit_count
     *
     * @mbggenerated
     */
    public Integer getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.day_visit_count
     *
     * @return the value of uc_member.day_visit_count
     *
     * @mbggenerated
     */
    public Integer getDayVisitCount() {
        return dayVisitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.day_visit_time
     *
     * @return the value of uc_member.day_visit_time
     *
     * @mbggenerated
     */
    public Date getDayVisitTime() {
        return dayVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.delete_flag
     *
     * @return the value of uc_member.delete_flag
     *
     * @mbggenerated
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.disable_flag
     *
     * @return the value of uc_member.disable_flag
     *
     * @mbggenerated
     */
    public Byte getDisableFlag() {
        return disableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.mobile_verify_flag
     *
     * @return the value of uc_member.mobile_verify_flag
     *
     * @mbggenerated
     */
    public Byte getMobileVerifyFlag() {
        return mobileVerifyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.email_verify_flag
     *
     * @return the value of uc_member.email_verify_flag
     *
     * @mbggenerated
     */
    public Byte getEmailVerifyFlag() {
        return emailVerifyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.audit_flag
     *
     * @return the value of uc_member.audit_flag
     *
     * @mbggenerated
     */
    public Byte getAuditFlag() {
        return auditFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.open_concat_flag
     *
     * @return the value of uc_member.open_concat_flag
     *
     * @mbggenerated
     */
    public Byte getOpenConcatFlag() {
        return openConcatFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.show_flag
     *
     * @return the value of uc_member.show_flag
     *
     * @mbggenerated
     */
    public Byte getShowFlag() {
        return showFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.email_remind_flag
     *
     * @return the value of uc_member.email_remind_flag
     *
     * @mbggenerated
     */
    public Byte getEmailRemindFlag() {
        return emailRemindFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.blog_flag
     *
     * @return the value of uc_member.blog_flag
     *
     * @mbggenerated
     */
    public Byte getBlogFlag() {
        return blogFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.realname_audit_status
     *
     * @return the value of uc_member.realname_audit_status
     *
     * @mbggenerated
     */
    public Byte getRealnameAuditStatus() {
        return realnameAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.audit_reason
     *
     * @return the value of uc_member.audit_reason
     *
     * @mbggenerated
     */
    public String getAuditReason() {
        return auditReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.expert_audit_status
     *
     * @return the value of uc_member.expert_audit_status
     *
     * @mbggenerated
     */
    public Byte getExpertAuditStatus() {
        return expertAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.expert_info_audit_status
     *
     * @return the value of uc_member.expert_info_audit_status
     *
     * @mbggenerated
     */
    public Byte getExpertInfoAuditStatus() {
        return expertInfoAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.enterprise_audit_status
     *
     * @return the value of uc_member.enterprise_audit_status
     *
     * @mbggenerated
     */
    public Byte getEnterpriseAuditStatus() {
        return enterpriseAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.enterprise_info_audit_status
     *
     * @return the value of uc_member.enterprise_info_audit_status
     *
     * @mbggenerated
     */
    public Byte getEnterpriseInfoAuditStatus() {
        return enterpriseInfoAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.mod_flag
     *
     * @return the value of uc_member.mod_flag
     *
     * @mbggenerated
     */
    public Byte getModFlag() {
        return modFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.res_mod_update
     *
     * @return the value of uc_member.res_mod_update
     *
     * @mbggenerated
     */
    public Date getResModUpdate() {
        return resModUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.safe_score
     *
     * @return the value of uc_member.safe_score
     *
     * @mbggenerated
     */
    public Integer getSafeScore() {
        return safeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.safe_next_id
     *
     * @return the value of uc_member.safe_next_id
     *
     * @mbggenerated
     */
    public Integer getSafeNextId() {
        return safeNextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.vip_level
     *
     * @return the value of uc_member.vip_level
     *
     * @mbggenerated
     */
    public Byte getVipLevel() {
        return vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.vip_startdate
     *
     * @return the value of uc_member.vip_startdate
     *
     * @mbggenerated
     */
    public Date getVipStartdate() {
        return vipStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_member.vip_enddate
     *
     * @return the value of uc_member.vip_enddate
     *
     * @mbggenerated
     */
    public Date getVipEnddate() {
        return vipEnddate;
    }
}